import type { Theme } from "./types";

export type ThemeTemplate = Omit<Theme, "id" | "isActive" | "createdAt" | "updatedAt">;

export const THEME_TEMPLATES: ThemeTemplate[] = [
  {
    name: "薄暮紫罗兰",
    slug: "twilight-violet",
    description: "温柔浪漫的紫色系，适合创意工作",
    uiStyle: "classic",
    darkBackground: "#1a0f29",
    darkForeground: "#f0e6ff",
    darkAccent: "#9d7dff",
    darkAccent2: "#b794ff",
    darkPanel: "#251a35",
    darkPanelStrong: "#332447",
    darkCardBg: "#1f1430",
    darkFieldBg: "#160c24",
    lightBackground: "#f8f5ff",
    lightForeground: "#2a1a3d",
    lightAccent: "#7c3aed",
    lightAccent2: "#9333ea",
    lightPanel: "#f3ebff",
    lightPanelStrong: "#ede0ff",
    lightCardBg: "#faf7ff",
    lightFieldBg: "#f5f0ff",
    useBackdropBlur: false,
    useGradientGlow: true,
    sortOrder: 100,
  },
  {
    name: "赛博霓虹",
    slug: "cyber-neon",
    description: "科技未来感，适合开发者和科技爱好者",
    uiStyle: "glass",
    darkBackground: "#0a0e1a",
    darkForeground: "#e0ffe0",
    darkAccent: "#00ff88",
    darkAccent2: "#00ffcc",
    darkPanel: "#12182a",
    darkPanelStrong: "#1a2438",
    darkCardBg: "#0d1220",
    darkFieldBg: "#080c16",
    lightBackground: "#f0f4f8",
    lightForeground: "#0a1a14",
    lightAccent: "#00d970",
    lightAccent2: "#00b894",
    lightPanel: "#e8f5f0",
    lightPanelStrong: "#d4ede3",
    lightCardBg: "#f0faf6",
    lightFieldBg: "#f5fcf8",
    useBackdropBlur: true,
    useGradientGlow: false,
    sortOrder: 101,
  },
  {
    name: "焦糖拿铁",
    slug: "caramel-latte",
    description: "温暖舒适的棕色调，适合长时间阅读",
    uiStyle: "wechat",
    darkBackground: "#1f1410",
    darkForeground: "#f5ebe0",
    darkAccent: "#e09e6a",
    darkAccent2: "#d4915f",
    darkPanel: "#2a1e18",
    darkPanelStrong: "#3a2820",
    darkCardBg: "#241a14",
    darkFieldBg: "#1a100c",
    lightBackground: "#faf6f1",
    lightForeground: "#2a1810",
    lightAccent: "#c07940",
    lightAccent2: "#a86b38",
    lightPanel: "#f5f0ea",
    lightPanelStrong: "#ede5dc",
    lightCardBg: "#fffbf6",
    lightFieldBg: "#f8f2ea",
    useBackdropBlur: false,
    useGradientGlow: false,
    sortOrder: 102,
  },
  {
    name: "北极冰蓝",
    slug: "arctic-ice",
    description: "冷静清澈的冰蓝色，提高专注力",
    uiStyle: "glass",
    darkBackground: "#0a1621",
    darkForeground: "#e0f2ff",
    darkAccent: "#5fe1ff",
    darkAccent2: "#38bdf8",
    darkPanel: "#12202e",
    darkPanelStrong: "#1a2a3c",
    darkCardBg: "#0d1a28",
    darkFieldBg: "#08121c",
    lightBackground: "#f0f9ff",
    lightForeground: "#0c2033",
    lightAccent: "#0ea5e9",
    lightAccent2: "#0284c7",
    lightPanel: "#e0f2fe",
    lightPanelStrong: "#bae6fd",
    lightCardBg: "#f0f9ff",
    lightFieldBg: "#e0f2fe",
    useBackdropBlur: true,
    useGradientGlow: false,
    sortOrder: 103,
  },
  {
    name: "抹茶拿铁",
    slug: "matcha-latte",
    description: "清新自然的绿色系，护眼舒适",
    uiStyle: "wechat",
    darkBackground: "#0f1910",
    darkForeground: "#e8f5e9",
    darkAccent: "#7ae582",
    darkAccent2: "#66d674",
    darkPanel: "#172820",
    darkPanelStrong: "#1f3328",
    darkCardBg: "#121e18",
    darkFieldBg: "#0c140e",
    lightBackground: "#f4fdf5",
    lightForeground: "#0f1910",
    lightAccent: "#22c55e",
    lightAccent2: "#16a34a",
    lightPanel: "#e8f5e9",
    lightPanelStrong: "#c8e6c9",
    lightCardBg: "#f1f8f4",
    lightFieldBg: "#e8f5e9",
    useBackdropBlur: false,
    useGradientGlow: false,
    sortOrder: 104,
  },
  {
    name: "珊瑚粉橙",
    slug: "coral-pink",
    description: "活力青春的粉橙色，充满能量",
    uiStyle: "classic",
    darkBackground: "#1f1214",
    darkForeground: "#ffe8e6",
    darkAccent: "#ff7a6b",
    darkAccent2: "#ff9688",
    darkPanel: "#2a1a1c",
    darkPanelStrong: "#3a2224",
    darkCardBg: "#241618",
    darkFieldBg: "#1a0e10",
    lightBackground: "#fff5f3",
    lightForeground: "#2a1214",
    lightAccent: "#ef4444",
    lightAccent2: "#f87171",
    lightPanel: "#fee2e2",
    lightPanelStrong: "#fecaca",
    lightCardBg: "#fff5f5",
    lightFieldBg: "#fee2e2",
    useBackdropBlur: false,
    useGradientGlow: true,
    sortOrder: 105,
  },
  {
    name: "午夜蓝调",
    slug: "midnight-blue",
    description: "深邃专注的深蓝色，适合夜间工作",
    uiStyle: "wechat",
    darkBackground: "#0c1428",
    darkForeground: "#e8ecf8",
    darkAccent: "#6b9aff",
    darkAccent2: "#5b88e5",
    darkPanel: "#141e38",
    darkPanelStrong: "#1c2847",
    darkCardBg: "#101a30",
    darkFieldBg: "#081020",
    lightBackground: "#f3f6fb",
    lightForeground: "#0c1428",
    lightAccent: "#2563eb",
    lightAccent2: "#1d4ed8",
    lightPanel: "#dbeafe",
    lightPanelStrong: "#bfdbfe",
    lightCardBg: "#eff6ff",
    lightFieldBg: "#dbeafe",
    useBackdropBlur: false,
    useGradientGlow: false,
    sortOrder: 106,
  },
  {
    name: "柠檬清晨",
    slug: "lemon-morning",
    description: "明亮愉悦的柠檬黄，提升心情",
    uiStyle: "classic",
    darkBackground: "#1a1a0a",
    darkForeground: "#fffef0",
    darkAccent: "#ffd93d",
    darkAccent2: "#ffc700",
    darkPanel: "#252518",
    darkPanelStrong: "#333320",
    darkCardBg: "#1f1f10",
    darkFieldBg: "#141408",
    lightBackground: "#fffef0",
    lightForeground: "#1a1a0a",
    lightAccent: "#eab308",
    lightAccent2: "#ca8a04",
    lightPanel: "#fef9c3",
    lightPanelStrong: "#fef08a",
    lightCardBg: "#fefce8",
    lightFieldBg: "#fef9c3",
    useBackdropBlur: false,
    useGradientGlow: true,
    sortOrder: 107,
  },
  {
    name: "樱花粉白",
    slug: "sakura-pink",
    description: "柔和梦幻的粉色系，温柔浪漫",
    uiStyle: "classic",
    darkBackground: "#1f0f14",
    darkForeground: "#ffe8f4",
    darkAccent: "#ffb3d9",
    darkAccent2: "#ff8fc7",
    darkPanel: "#2a1a20",
    darkPanelStrong: "#3a242e",
    darkCardBg: "#241418",
    darkFieldBg: "#1a0c10",
    lightBackground: "#fff5fa",
    lightForeground: "#2a1014",
    lightAccent: "#ec4899",
    lightAccent2: "#db2777",
    lightPanel: "#fce7f3",
    lightPanelStrong: "#fbcfe8",
    lightCardBg: "#fdf2f8",
    lightFieldBg: "#fce7f3",
    useBackdropBlur: false,
    useGradientGlow: true,
    sortOrder: 108,
  },
  {
    name: "翡翠森林",
    slug: "emerald-forest",
    description: "沉稳自然的翡翠绿，贴近自然",
    uiStyle: "wechat",
    darkBackground: "#0a1a14",
    darkForeground: "#e0f5ed",
    darkAccent: "#52d4a0",
    darkAccent2: "#3dbf8f",
    darkPanel: "#122620",
    darkPanelStrong: "#1a332c",
    darkCardBg: "#0d1f18",
    darkFieldBg: "#08140f",
    lightBackground: "#f0fdf7",
    lightForeground: "#0a1a14",
    lightAccent: "#10b981",
    lightAccent2: "#059669",
    lightPanel: "#d1fae5",
    lightPanelStrong: "#a7f3d0",
    lightCardBg: "#ecfdf5",
    lightFieldBg: "#d1fae5",
    useBackdropBlur: false,
    useGradientGlow: false,
    sortOrder: 109,
  },
  {
    name: "落日余晖",
    slug: "sunset-glow",
    description: "温暖宁静的橙色调，像傍晚的余晖",
    uiStyle: "classic",
    darkBackground: "#1f1410",
    darkForeground: "#fff0e8",
    darkAccent: "#ff8f47",
    darkAccent2: "#ff7a33",
    darkPanel: "#2a1e18",
    darkPanelStrong: "#3a2820",
    darkCardBg: "#241a14",
    darkFieldBg: "#1a100c",
    lightBackground: "#fff8f0",
    lightForeground: "#1f1410",
    lightAccent: "#f97316",
    lightAccent2: "#ea580c",
    lightPanel: "#ffedd5",
    lightPanelStrong: "#fed7aa",
    lightCardBg: "#fff7ed",
    lightFieldBg: "#ffedd5",
    useBackdropBlur: false,
    useGradientGlow: true,
    sortOrder: 110,
  },
  {
    name: "极夜黑白",
    slug: "polar-night",
    description: "极简高对比的纯黑白配色",
    uiStyle: "minimal",
    darkBackground: "#000000",
    darkForeground: "#ffffff",
    darkAccent: "#ffffff",
    darkAccent2: "#e0e0e0",
    darkPanel: "#0a0a0a",
    darkPanelStrong: "#141414",
    darkCardBg: "#000000",
    darkFieldBg: "#1a1a1a",
    lightBackground: "#ffffff",
    lightForeground: "#000000",
    lightAccent: "#000000",
    lightAccent2: "#404040",
    lightPanel: "#ffffff",
    lightPanelStrong: "#f5f5f5",
    lightCardBg: "#ffffff",
    lightFieldBg: "#fafafa",
    useBackdropBlur: false,
    useGradientGlow: false,
    sortOrder: 111,
  },
];
